name: EthicalCheck-Workflow
on:
  push:
    branches: [ "master", "*master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '30 4 * * 3'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  Trigger_EthicalCheck:
    permissions:
      security-events: write 
      actions: read 
    runs-on: ubuntu-latest
    steps:
       - name: EthicalCheck  Free & Automated API Security Testing Service
         uses: apisec-inc/ethicalcheck-action@005fac321dd843682b1af6b72f30caaf9952c641
         with:
          oas-url: "http://netbanking.apisec.ai:8080/v2/api-docs"
          email: "apetree1001@email.phoenix.edu"
          sarif-result-file: "ethicalcheck-results.sarif"
       - name: Upload sarif file to repository
         uses: github/codeql-action/upload-sarif@v2
         with:
          sarif_file: ./ethicalcheck-results.sarif
